version: '3.8'

services:
  web:
    build: .
    command: ./start.sh
    volumes:
      - ./:/app:cached
      - /app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your-secret-key
      - DEBUG=True
      - POSTGRES_DB=kusaidia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/kusaidia
      - SQL_HOST=db
      - SQL_PORT=5432      
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - HF_TOKEN=your-huggingface-token
    depends_on:
      - db
      - redis
    networks:
      - easygov-network

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./:/app:cached
    environment:
      - DJANGO_SECRET_KEY=your-secret-key
      - DEBUG=True
      - POSTGRES_DB=kusaidia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/kusaidia
      - SQL_HOST=db
      - SQL_PORT=5432 
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - HF_TOKEN=your-huggingface-token
    depends_on:
      - db
      - redis
      - web
    networks:
      - easygov-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kusaidia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - easygov-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - easygov-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  easygov-network:
    driver: bridge

volumes:
  postgres_data: