services:
  - type: web
    name: easygov-backend
    env: docker
    plan: free
    region: Oregon (US West)
    repo: https://github.com/ma-za-kpe/EasyGov
    branch: main
    dockerCommand: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    preDeployCommand: python manage.py migrate && python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: kusaidia_db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: easygov-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: easygov-redis
          type: redis
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: "easygov.onrender.com"
      - key: STATIC_ROOT
        value: /app/staticfiles
      - key: HF_TOKEN
        sync: false # Add manually in Dashboard
      - key: PYTHONUNBUFFERED
        value: 1

  - type: worker
    name: easygov-worker
    env: docker
    plan: free
    region: Oregon (US West)
    repo: https://github.com/ma-za-kpe/EasyGov
    branch: main
    dockerCommand: celery -A app worker --loglevel=info
    user: appuser
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: kusaidia_db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: easygov-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: easygov-redis
          type: redis
          property: connectionString
      - key: HF_TOKEN
        sync: false # Add manually in Dashboard
      - key: PYTHONUNBUFFERED
        value: 1

  - type: redis
    name: easygov-redis
    plan: free
    region: Oregon (US West)
    ipAllowList: [] # Internal connections only
    maxmemoryPolicy: noeviction

databases:
  - name: kusaidia_db
    databaseName: kusaidia_db
    user: kusaidia_db_user
    plan: free
    region: Oregon (US West)