# Generated by Django 5.2 on 2025-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summarization_processed',
            field=models.BooleanField(default=False),
        ),
    ]
