# Generated by Django 5.2 on 2025-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_summarization_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('document', 'language')},
        ),
    ]
