# Generated by Django 5.2 on 2025-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_is_verified_document_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
