# Generated by Django 5.2 on 2025-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_summary_explanation_summary_original_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='should_summarize',
            field=models.BooleanField(default=True, help_text='Uncheck to add document without auto-summarization'),
        ),
    ]
