# Generated by Django 4.2.20 on 2025-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_should_summarize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='language',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=10),
        ),
    ]
