# Generated by Django 4.2.20 on 2025-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_summary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
